### ISSUE TITLE
GPU does not work!

### ISSUE THREAD

**Issue by difan0224** [HewlettPackard/swarm-learning#18]
It seems that I can not use GPU to run MNIST on TF or PYT?

Could you please show me your training procedure?

**Comment by RadhakrishnaJ** [comment]
Hello,

Machine Learning execution through PyTorch does not support GPU usage currently. 

Machine Learning execution through TensorFlow supports GPU usage. Please follow the instructions under “Starting the SL nodes” in [https://github.com/HewlettPackard/swarm-learning/blob/master/docs/RunningSL.md](url)

•	--gpu=<set of GPUs to use>
This parameter specifies the GPUs to use. A Swarm Learning node can use multiple GPUs. The set of GPUs to use can be specified in one of two ways:
a. A comma-separated list of GPU indexes -- GPU indexes start from zero.
b. all -- all GPUs on the system are used.
This parameter is optional. When it is not specified, the Swarm Learning nodes will run on the CPU only and will not use any GPU.

**Comment by difan0224** [comment]
Thanks! May I know your email address?

**Comment by RadhakrishnaJ** [comment]
I can able to access the link. 

You can do as mentioned below to get onto same section. 
From main SWARM LEARNING read_me go to “Documentation”. Follow “Configuring and Running Swarm Learning Components” link.  Refer “Starting the SL nodes” section for GPU usage instructions. 

Please try and confirm GPU utilization, so that this issue can be closed. 
For any discussion needs please use discussions forum.

**Comment by malikre** [comment]
Closing the issue as the reported issue has been addressed with reference link corrected. Please open a new issue in case any further assistance required.
