### ISSUE TITLE
How to add new modules to the swarm learning pipeline

### ISSUE THREAD

**Issue by oliversaldanha25** [HewlettPackard/swarm-learning#30]
I have a specific code which needed open-CV for the and i want to try swarm learning. 
I have edited the example mnist-pytorch example.
Created a new workspace with my code  and data.
When i am running the training it says that module not found.
Can anyone guide me how to run the swarm learning for my project.
I would really appreciate if i get any support. I have been working with the swarm learning from last 3 weeks .
Regards
Oliver

**Comment by RadhakrishnaJ** [comment]
Hello, 

I appreciate your efforts regard this. Please follow the steps mentioned below. 

For any additional packages support to machine learning process, user has to do following.
1.	Write a dockerfile to create a local SL image
• By extending FROM the default SL image (sl-tf or sl-pyt).
• Add required additional packages
2.	Build the local SL image from above dockerfile.
3.	If local SL image name differs from default SL image, then update ‘common’ script (inside swarm-learning/bin) and make sure following lines uses local SL image.
slTFImage="${swarmDockerHubAndUser}/sl-tf:${swarmVer}" (or)
slPytImage="${swarmDockerHubAndUser}/sl-pyt:${swarmVer}"
4.	As usual run the container using run-sl command.

**Comment by lanjinraol** [comment]
I follow these steps， then I got：
![WeChat364239f3440a095b22eb90f85eeb609b](https://user-images.githubusercontent.com/22259266/126057264-d5560c83-60fc-4e18-93e2-9007389c5ff1.png)

WARN[0030] received EOF, stopping recv loop              err="rpc error: code = Unavailable desc = transport is closing" subsystem_name=external_plugin.swarm.stdio
ERRO[0030] Agent crashed                                 error="create attestation client: failed to dial dns:///172.17.0.3:8081: context deadline exceeded: connection error: desc = \"transport: authentication handshake failed: x509svid: could not verify leaf certificate: x509: certificate signed by unknown authority (possibly because of \\\"x509: ECDSA verification failure\\\" while trying to verify candidate authority certificate \\\"Swarm-Learning\\\")\""

**Comment by RadhakrishnaJ** [comment]
> I follow these steps， then I got：
> ![WeChat364239f3440a095b22eb90f85eeb609b](https://user-images.githubusercontent.com/22259266/126057264-d5560c83-60fc-4e18-93e2-9007389c5ff1.png)
> 
> WARN[0030] received EOF, stopping recv loop err="rpc error: code = Unavailable desc = transport is closing" subsystem_name=external_plugin.swarm.stdio
> ERRO[0030] Agent crashed error="create attestation client: failed to dial dns:///172.17.0.3:8081: context deadline exceeded: connection error: desc = "transport: authentication handshake failed: x509svid: could not verify leaf certificate: x509: certificate signed by unknown authority (possibly because of \"x509: ECDSA verification failure\" while trying to verify candidate authority certificate \"Swarm-Learning\")""

Hello, 
Could you please share your Dockerfile?

**Comment by oliversaldanha25** [comment]
the problem was solved
