### ISSUE TITLE
How to simulate offline nodes?

### ISSUE THREAD

**Issue by hanjialiang** [HewlettPackard/swarm-learning#50]
Hello, I am considering a scenario that some of the SL nodes become offline during the training process. If the online SL nodes are more than min_peers, the SL training process can still continue.
However, I wonder how those offline nodes would be initialized when they come back online. Will the SL network consider the learnings of the offline nodes, to merge a new model? Or, will the SL network abandon the learnings of the offline nodes, and simply initialize them with merged models of online SL nodes in the latest batch?
Besides, when I try to simulate this scenario,  I get an error called "SMLBB: Node enrolled cannot change ML context". Does SL support manually removing some epochs or batches from synchronization? If so, how can I implement this feature?
I really appreciate it if you provide me some hints. Thank you!

**Comment by maghsk** [comment]
Does setting a dynamic sync interval without using adaptive sync solve this problem? I know PyTorch could set a dynamic sync interval. But what about Keras?

**Comment by RadhakrishnaJ** [comment]
Please refer FAQ regarding offline node question [What happens if a node runs slowly or drops out of the network?](https://github.com/HewlettPackard/swarm-learning/blob/master/docs/FAQ.md#what-happens-if-a-node-runs-slowly-or-drops-out-of-the-network)

Regarding "SMLBB: Node enrolled cannot change ML context" error - Swarm does not expect any configuration changes when node goes offline and comes back.
